# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Verify required files
        run: |
          if [ ! -f index.html ]; then
            echo "::error::index.html file is missing!"
            exit 1
          fi
          if [ ! -f script.js ]; then
            echo "::error::script.js file is missing!"
            exit 1
          fi
          echo "All required files present"
          
      - name: Add .nojekyll file
        run: touch .nojekyll
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: none
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            index.html
            script.js
            .nojekyll
            # Add other assets if needed
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Show deployment URL
        run: |
          echo "Deployment successful! Your site is now live at:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
